import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN", "YOUR_BOT_TOKEN")

CHANNEL_ID = "@quizzy_best"
YOOKASSA_PROVIDER_TOKEN = os.getenv("YOOKASSA_PROVIDER_TOKEN")
OWNER_ID = int(os.getenv("OWNER_ID", "228592391"))

TICKET_LIMIT = 3500
INITIAL_FAKE_TICKETS = 741
MAX_TICKET_NUMBER = 50000

GOOGLE_CREDS_JSON = os.getenv("GOOGLE_CREDS_JSON")
SPREADSHEET_ID = "1dJ2AFECSBqoIJQkzfXPmdxVr8DSWPpuufU_l88mZD-Y"
